import type { Brand, CategoryTile, Product } from "@/types";

// Temporary build-time data for the homepage. Replaced by the InsForge
// `brands` / `products` tables once the affiliate catalog sync (Phase 2) lands.
// Images are placeholders (Picsum/DiceBear) — never real brand photography.

export const FEATURED_BRANDS: Brand[] = [
  {
    id: "brand-nike",
    name: "Nike",
    slug: "nike",
    logoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=Nike&backgroundType=solid&backgroundColor=ffffff",
    description: "Performance footwear and sportswear.",
    category: "fashion",
    isFeatured: true,
  },
  {
    id: "brand-zara",
    name: "Zara",
    slug: "zara",
    logoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=Zara&backgroundType=solid&backgroundColor=ffffff",
    description: "Contemporary fashion for women and men.",
    category: "fashion",
    isFeatured: true,
  },
  {
    id: "brand-sephora",
    name: "Sephora",
    slug: "sephora",
    logoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=Sephora&backgroundType=solid&backgroundColor=ffffff",
    description: "Beauty, skincare, and fragrance.",
    category: "beauty",
    isFeatured: true,
  },
  {
    id: "brand-apple",
    name: "Apple",
    slug: "apple",
    logoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=Apple&backgroundType=solid&backgroundColor=ffffff",
    description: "Premium consumer technology.",
    category: "tech",
    isFeatured: true,
  },
  {
    id: "brand-adidas",
    name: "Adidas",
    slug: "adidas",
    logoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=Adidas&backgroundType=solid&backgroundColor=ffffff",
    description: "Sportswear and lifestyle footwear.",
    category: "fashion",
    isFeatured: true,
  },
  {
    id: "brand-mango",
    name: "Mango",
    slug: "mango",
    logoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=Mango&backgroundType=solid&backgroundColor=ffffff",
    description: "Modern Mediterranean-inspired fashion.",
    category: "fashion",
    isFeatured: true,
  },
  {
    id: "brand-gucci",
    name: "Gucci",
    slug: "gucci",
    logoUrl: "https://api.dicebear.com/9.x/initials/svg?seed=Gucci&backgroundType=solid&backgroundColor=ffffff",
    description: "Italian luxury fashion house.",
    category: "luxury",
    isFeatured: true,
  },
];

export const FEATURED_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    title: "Air Max Pulse Sneakers",
    brandName: "Nike",
    category: "fashion",
    imageUrl: "/shoes/shoe-7.avif",
    priceAmount: 160,
    priceCurrency: "USD",
    vendorName: "Nike",
    vendorUrl: "https://www.nike.com",
    isFeatured: true,
    tag: "new",
  },
  {
    id: "prod-2",
    title: "Oversized Wool-Blend Coat",
    brandName: "Zara",
    category: "fashion",
    imageUrl: "/assets/coat.jpg",
    priceAmount: 129,
    priceCurrency: "GBP",
    vendorName: "Zara",
    vendorUrl: "https://www.zara.com",
    isFeatured: true,
    tag: "bestseller",
  },
  {
    id: "prod-3",
    title: "Sephora Favorites Skincare Set",
    brandName: "Sephora",
    category: "beauty",
    imageUrl: "/assets/makeup.jpg",
    priceAmount: 65,
    priceCurrency: "USD",
    vendorName: "Sephora",
    vendorUrl: "https://www.sephora.com",
    isFeatured: true,
    tag: "new",
  },
  {
    id: "prod-4",
    title: "AirPods Pro (2nd Gen)",
    brandName: "Apple",
    category: "tech",
    imageUrl: "/assets/airpod.jpg",
    priceAmount: 249,
    priceCurrency: "USD",
    vendorName: "Apple",
    vendorUrl: "https://www.apple.com",
    isFeatured: true,
    tag: "bestseller",
  },
  {
    id: "prod-5",
    title: "Ultraboost Light Running Shoes",
    brandName: "Adidas",
    category: "fashion",
    imageUrl: "/shoes/shoe-11.avif",
    priceAmount: 190,
    priceCurrency: "USD",
    vendorName: "Adidas",
    vendorUrl: "https://www.adidas.com",
    isFeatured: true,
    tag: "new",
  },
  {
    id: "prod-6",
    title: "Pleated Midi Skirt",
    brandName: "Mango",
    category: "fashion",
    imageUrl: "/assets/skirt.jpg",
    priceAmount: 60,
    priceCurrency: "EUR",
    vendorName: "Mango",
    vendorUrl: "https://shop.mango.com",
    isFeatured: true,
    tag: "bestseller",
  },
  {
    id: "prod-7",
    title: "Rouge Hermès Lipstick",
    brandName: "Sephora",
    category: "beauty",
    imageUrl: "/assets/brush.jpg",
    priceAmount: 53,
    priceCurrency: "USD",
    vendorName: "Sephora",
    vendorUrl: "https://www.sephora.com",
    isFeatured: true,
    tag: "new",
  },
  {
    id: "prod-8",
    title: "Dyson Supersonic Hair Dryer",
    brandName: "Dyson",
    category: "tech",
    imageUrl: "/assets/dryer.jpg",
    priceAmount: 429,
    priceCurrency: "USD",
    vendorName: "Dyson",
    vendorUrl: "https://www.dyson.com",
    isFeatured: true,
    tag: "bestseller",
  },
];

export const CATALOG_PRODUCTS: Product[] = [
  ...FEATURED_PRODUCTS.map((product) => ({
    ...product,
    source: (product.brandName === "Apple" || product.brandName === "Sephora" ? "US" : "UK") as "US" | "UK",
  })),
  {
    id: "prod-9",
    title: "Classic Leather Tote",
    brandName: "Zara",
    category: "fashion",
    imageUrl: "/shoes/shoe-1.avif",
    priceAmount: 84,
    priceCurrency: "USD",
    vendorName: "Zara",
    vendorUrl: "https://www.zara.com",
    isFeatured: false,
    tag: "new",
    source: "UK",
  },
  {
    id: "prod-10",
    title: "Studio Glow Serum",
    brandName: "Sephora",
    category: "beauty",
    imageUrl: "/shoes/shoe-2.avif",
    priceAmount: 42,
    priceCurrency: "USD",
    vendorName: "Sephora",
    vendorUrl: "https://www.sephora.com",
    isFeatured: true,
    tag: "bestseller",
    source: "US",
  },
  {
    id: "prod-11",
    title: "Minimalist Smart Lamp",
    brandName: "Apple",
    category: "tech",
    imageUrl: "/shoes/shoe-3.avif",
    priceAmount: 120,
    priceCurrency: "USD",
    vendorName: "Apple",
    vendorUrl: "https://www.apple.com",
    isFeatured: false,
    source: "US",
  },
  {
    id: "prod-12",
    title: "Woven Accent Basket",
    brandName: "Mango",
    category: "home",
    imageUrl: "/shoes/shoe-4.avif",
    priceAmount: 35,
    priceCurrency: "USD",
    vendorName: "Mango",
    vendorUrl: "https://shop.mango.com",
    isFeatured: true,
    tag: "new",
    source: "UK",
  },
  {
    id: "prod-13",
    title: "Playful Kids Backpack",
    brandName: "Nike",
    category: "kids",
    imageUrl: "/shoes/shoe-5.avif",
    priceAmount: 58,
    priceCurrency: "USD",
    vendorName: "Nike",
    vendorUrl: "https://www.nike.com",
    isFeatured: false,
    source: "US",
  },
  {
    id: "prod-14",
    title: "Velvet Travel Set",
    brandName: "Adidas",
    category: "fashion",
    imageUrl: "/shoes/shoe-6.avif",
    priceAmount: 78,
    priceCurrency: "USD",
    vendorName: "Adidas",
    vendorUrl: "https://www.adidas.com",
    isFeatured: true,
    tag: "bestseller",
    source: "UK",
  },
  {
    id: "prod-15",
    title: "Signature Fragrance Duo",
    brandName: "Sephora",
    category: "beauty",
    imageUrl: "/shoes/shoe-7.avif",
    priceAmount: 92,
    priceCurrency: "USD",
    vendorName: "Sephora",
    vendorUrl: "https://www.sephora.com",
    isFeatured: false,
    source: "US",
  },
  {
    id: "prod-16",
    title: "Compact Foldable Speaker",
    brandName: "Apple",
    category: "tech",
    imageUrl: "/shoes/shoe-8.avif",
    priceAmount: 149,
    priceCurrency: "USD",
    vendorName: "Apple",
    vendorUrl: "https://www.apple.com",
    isFeatured: true,
    tag: "new",
    source: "US",
  },
  {
    id: "prod-17",
    title: "Soft Knit Lounge Set",
    brandName: "Zara",
    category: "fashion",
    imageUrl: "/shoes/shoe-9.avif",
    priceAmount: 64,
    priceCurrency: "GBP",
    vendorName: "Zara",
    vendorUrl: "https://www.zara.com",
    isFeatured: true,
    tag: "bestseller",
    source: "UK",
  },
  {
    id: "prod-18",
    title: "Glow Mist Toner",
    brandName: "Sephora",
    category: "beauty",
    imageUrl: "/shoes/shoe-10.avif",
    priceAmount: 31,
    priceCurrency: "USD",
    vendorName: "Sephora",
    vendorUrl: "https://www.sephora.com",
    isFeatured: false,
    source: "US",
  },
  {
    id: "prod-19",
    title: "Ceramic Desk Organizer",
    brandName: "Mango",
    category: "home",
    imageUrl: "/shoes/shoe-11.avif",
    priceAmount: 48,
    priceCurrency: "USD",
    vendorName: "Mango",
    vendorUrl: "https://shop.mango.com",
    isFeatured: true,
    tag: "new",
    source: "UK",
  },
  {
    id: "prod-20",
    title: "Mini Adventure Trike",
    brandName: "Nike",
    category: "kids",
    imageUrl: "/shoes/shoe-12.avif",
    priceAmount: 89,
    priceCurrency: "USD",
    vendorName: "Nike",
    vendorUrl: "https://www.nike.com",
    isFeatured: false,
    source: "US",
  },
  {
    id: "prod-21",
    title: "Cloud Runner Sneakers",
    brandName: "Adidas",
    category: "fashion",
    imageUrl: "/shoes/shoe-13.avif",
    priceAmount: 112,
    priceCurrency: "USD",
    vendorName: "Adidas",
    vendorUrl: "https://www.adidas.com",
    isFeatured: true,
    tag: "bestseller",
    source: "UK",
  },
  {
    id: "prod-22",
    title: "Silk Sleep Mask",
    brandName: "Sephora",
    category: "beauty",
    imageUrl: "/shoes/shoe-14.avif",
    priceAmount: 24,
    priceCurrency: "USD",
    vendorName: "Sephora",
    vendorUrl: "https://www.sephora.com",
    isFeatured: false,
    source: "US",
  },
  {
    id: "prod-23",
    title: "Portable Charging Case",
    brandName: "Apple",
    category: "tech",
    imageUrl: "/shoes/shoe-15.avif",
    priceAmount: 69,
    priceCurrency: "USD",
    vendorName: "Apple",
    vendorUrl: "https://www.apple.com",
    isFeatured: false,
    source: "US",
  },
  {
    id: "prod-24",
    title: "Weekend Utility Bag",
    brandName: "Mango",
    category: "fashion",
    imageUrl: "/assets/hero-image.avif",
    priceAmount: 74,
    priceCurrency: "EUR",
    vendorName: "Mango",
    vendorUrl: "https://shop.mango.com",
    isFeatured: true,
    tag: "new",
    source: "UK",
  },
];

export const HOME_CATEGORY_TILES: CategoryTile[] = [
  { slug: "fashion", name: "Fashion", imageUrl: "/shoes/shoe-3.avif" },
  { slug: "beauty", name: "Beauty", imageUrl: "/shoes/shoe-4.avif" },
  { slug: "tech", name: "Tech", imageUrl: "/shoes/shoe-5.avif" },
  { slug: "fragrance", name: "Fragrance", imageUrl: "/shoes/shoe-6.avif" },
];

export const HOME_PROMO_BANNERS: CategoryTile[] = [
  { slug: "baby", name: "Baby & Kids Essentials", imageUrl: "/shoes/shoe-1.avif" },
  { slug: "home", name: "Home & Living", imageUrl: "/shoes/shoe-2.avif" },
];
